#!/bin/bash
#
# Prepares the init.d script to start/stop the installed WLS domain.
# The created init.d script must be then installed manually as root
# Created: 2017-09-25 dkovacs of virtual7
#
# 2018-07-05    Separated ASERVER_HOME and MSERVER_HOME (dkovacs)
# 2018-08-03    Fixed to start/stop local components only instead of all (dkovacs)
cd "$(dirname $0)/.."; export workdir="$(pwd)"
. $workdir/script/functions.sh


# Create the init.d script
cat >/tmp/weblogic-$DOMAIN_NAME <<EOF
#!/bin/bash
#
# weblogic - Starts and stops WebLogic Doman $DOMAIN_NAME
#
# chkconfig:   345 85 15
# description: Starts and stops WebLogic Domain $DOMAIN_NAME
# Generated by the IuK37 standard WLS installer by virtual7 GmbH

### BEGIN INIT INFO
# Provides: weblogic-$DOMAIN_NAME
# Required-Start: \$network \$local_fs nfs
# Required-Stop: \$network \$local_fs nfs
# Should-Start:
# Should-Stop:
# Default-Start: 3 5
# Default-Stop: 0 1 2 4 6
# Short-Description: WebLogic Domain $DOMAIN_NAME
# Description: Starts and stops WebLogic Domain $DOMAIN_NAME
### END INIT INFO

SERVICE_NAME=weblogic-$DOMAIN_NAME
RETVAL=0

export PATH=/usr/local/bin:/usr/bin:/bin

log="$LOGDIR_PATH/$WLS_OS_USER/$DOMAIN_NAME/init/$(hostname)/init.log"

start() {
        echo -n \$"Starting \$SERVICE_NAME: "

        # Start Domain $DOMAIN_NAME
        echo "\$(date '+%Y-%m-%d %H:%M:%S'): ---------- Starting \$SERVICE_NAME ----------" >>\$log
        /bin/su $WLS_OS_USER -c "$ASERVER_HOME/custom_scripts/command-control.sh nmstart $(hostname)" >>"\$log" 2>&1
        /bin/su $WLS_OS_USER -c "$ASERVER_HOME/custom_scripts/command-control.sh multistart $ADMINSERVER_NAME $(hostname)" >>"\$log" 2>&1
        RETVAL=\$?
        echo
}

stop() {
        echo -n "Stopping \$SERVICE_NAME: "

        # Stop Domain $DOMAIN_NAME
        echo "\$(date '+%Y-%m-%d %H:%M:%S'): ---------- Stopping \$SERVICE_NAME ----------" >>\$log
        /bin/su $WLS_OS_USER -c "$ASERVER_HOME/custom_scripts/command-control.sh multistop $ADMINSERVER_NAME $(hostname)" >>"\$log" 2>&1
        /bin/su $WLS_OS_USER -c "$ASERVER_HOME/custom_scripts/command-control.sh nmstop $(hostname)" >>"\$log" 2>&1
        RETVAL=\$?
        echo
}

case "\$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  *)
        echo "Usage: \$0 {start|stop}"
        exit 1
esac

exit \$RETVAL
EOF

# Create a script for installing the init.d script
cat >/tmp/runAsRoot-$DOMAIN_NAME.sh <<EOF
#!/bin/bash
if [ \$(whoami) != root ]; then
  echo "You need to be root to run this script. Exiting."
  exit 1
fi
chown root.root /tmp/weblogic-$DOMAIN_NAME &&
  chmod 744 /tmp/weblogic-$DOMAIN_NAME &&
  mv /tmp/weblogic-$DOMAIN_NAME /etc/init.d/ &&
  chkconfig --add weblogic-$DOMAIN_NAME
EOF
chmod 755 /tmp/runAsRoot-$DOMAIN_NAME.sh
